import type { LicenseRow } from './types'

export const LICENSE_SAMPLE_DATA: readonly LicenseRow[] = [
  {
    no: 1,
    licenseName: 'Academic Free License v3.0',
    spdxIdentifier: 'AFL-3.0',
    nickName: 'Academic Free License 3.0\nAFL 3.0',
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: 'Network Triggered',
    webpage: 'https://spdx.org/licenses/AFL-3.0.html',
    webpageList: null,
    descriptionKo: '배포의 범위에 네트워크서비스도 포함',
  },
  {
    no: 1,
    licenseName: 'BSD 2-Clause NetBSD License',
    spdxIdentifier: 'BSD-2-Clause-NetBSD',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://www.netbsd.org/about/redistribution.html#default',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 2,
    licenseName: 'CNRI Jython License',
    spdxIdentifier: 'CNRI-Jython',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/jython/jython/blob/master/LICENSE.txt',
    webpageList: 'https://www.jython.org/jython-old-sites/license.html',
    descriptionKo: null,
  },
  {
    no: 3,
    licenseName: 'Nunit',
    spdxIdentifier: 'Nunit',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://docs.nunit.org/2.5/license.html',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 4,
    licenseName: 'Eclipse Distribution License - v 1.0',
    spdxIdentifier: 'LicenseRef-Eclipse-Distribution-License-v1.0',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://www.eclipse.org/org/documents/edl-v10.php',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 5,
    licenseName: 'Boehm-Demers-Weiser GC License',
    spdxIdentifier: 'Boehm-GC',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/bdwgc/bdwgc/blob/master/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 6,
    licenseName: 'PCRE2 exception',
    spdxIdentifier: 'PCRE2-exception',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/PCRE2Project/pcre2/blob/master/LICENCE.md',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 7,
    licenseName: 'LLVM Exception',
    spdxIdentifier: 'LLVM-exception',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://llvm.org/LICENSE.txt',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 8,
    licenseName: 'Zlib-like License (stephan-brumme)',
    spdxIdentifier: 'LicenseRef-Zlib-like-License-stephan-brumme',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://create.stephan-brumme.com/disclaimer.html',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 9,
    licenseName: 'MIT-like License (OneSignal-iOS-SDK)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-OneSignal-iOS-SDK',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/OneSignal/OneSignal-iOS-SDK/blob/main/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 10,
    licenseName: 'MIT-like License (stk)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-stk',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/thestk/stk/blob/master/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 11,
    licenseName: 'MIT-like License (Kodeco)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-Kodeco',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: 'Purpose Restriction',
    webpage: 'https://github.com/kodecocodes/alg-materials/blob/editions/5.0/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 12,
    licenseName: 'MIT-like License (JSONExport)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-JSonExport',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/Ahmed-Ali/JSONExport/blob/master/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 13,
    licenseName: 'MIT-like License (MWFeedParser)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-MWFeedParser',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: 'Purpose Restriction',
    webpage: 'https://github.com/mwaterfall/MWFeedParser/blob/master/LICENSE.txt',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 14,
    licenseName: 'MIT-like License (pngquant)',
    spdxIdentifier: 'LicenseRef-MIT-like-License-pngquant',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/kornelski/pngquant/blob/main/COPYRIGHT',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 15,
    licenseName: 'BSD-like License (XMPPFramework)',
    spdxIdentifier: 'LicenseRef-BSD-like-License-XMPPFramework',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/robbiehanson/XMPPFramework/blob/master/copying.txt',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 16,
    licenseName: 'BSD-like License (TriCRF)',
    spdxIdentifier: 'LicenseRef-BSD-like-License-TriCRF',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://github.com/minwoo/TriCRF/blob/master/LICENSE',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 17,
    licenseName: 'BSD-like License (Lemur)',
    spdxIdentifier: 'LicenseRef-BSD-like-License-Lemur',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: null,
    webpage: 'https://sourceforge.net/p/lemur/code/HEAD/tree/indri/trunk/LICENSE.txt',
    webpageList: null,
    descriptionKo: null,
  },
  {
    no: 18,
    licenseName: 'Sustainable Use License v1.0',
    spdxIdentifier: 'SUL-1.0',
    nickName: null,
    obligationNotice: true,
    obligationDisclosingSrc: 'NONE',
    restriction: 'Internal Use Only',
    webpage: 'https://github.com/n8n-io/n8n/blob/master/LICENSE.md',
    webpageList: null,
    descriptionKo: null,
  },
]
